[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
local = "http://127.0.0.1:8545"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }